#!/bin/bash

# osascript ~/bin/set-size.scpt $*

exec osascript - $* <<EOF
on run argv
        tell application "Terminal"
                activate
                with timeout of 1800 seconds
                        tell front window
                                set number of columns to item 1 of argv
                                set number of rows to item 2 of argv
                        end tell
                end timeout
        end tell
end run
EOF
