#!/bin/bash

# for all qa users, return what branch they're currently working on.

for QA_USER in `cat $ST_SRC_BASE/stconfig/personal/qa/qausers` ; do
    echo -n $QA_USER

    if cd /home/$QA_USER/src/st/socialtext >& /dev/null ; then
        git-branch | egrep '\*'
    else
        echo ' <unknown>'
    fi
done
