#!/usr/bin/zsh

################################################################
# prompt v0.0.1 for use with Bash on Darwin-OSX ......
# by Gary Kerbaugh
# Send comments, bugs or money to gkerbaugh@nc.rr.com
#
# Source this file from you .bashrc to set your prompt to a colored prompt including
# the PWD trimmed, tcsh-style, to the last 3 levels. Also the history number is colored
# by success of the last command.
#
# This program is free software; you can redistribute it and/or modify 
# it under the terms of the GNU General Public License as published by 
# the Free Software Foundation; either version 2 of the License, or 
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
# GNU General Public License for more details.
################################################################

alias kevblog='picblog --tag '\''Daily Blog'\'' --tag '\''Daily Dev Blog'\'' --tag "Kevin'\''s Dev Log" --name kevinj --user kevin.jones@socialtext.com --pass monday --workspace stoss --server http://www.socialtext.net'

alias dtrad='wikrad --server https://www2.socialtext.net --workspace dev-tasks'

PATH="$PATH:/usr/share/stconfig/stbin"
selenium_host=bonobo

# ZSH specific stuff from here on
ls =ls >/dev/null 2>&1 || exec "zsh"

RPS1=''
eval $(dircolors | perl -pe 's/di=01;34/di=01;36/')
unsetopt print_exit_value
bindkey "^R" history-incremental-search-backward
setopt BASH_AUTO_LIST
setopt NO_AUTO_MENU
setopt NO_ALWAYS_LAST_PROMPT
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
HISTFILE=~/.zsh_history
SAVEHIST=1000
HISTSIZE=1000
zstyle ':completion:*' list-colors ''
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' squeeze-slashes true

#--------------------------------------------------------------------------------------------------------------------
# function issucceed: Sets the "HISTORY_COLOR" based on the success of the previous command
#--------------------------------------------------------------------------------------------------------------------
function issucceed
{
	if [ "$1" -eq 0 ]; then
		HIST_COLOR="$BOLD_RED"
		PREFIX=""
	else
		HIST_COLOR="$BOLD_YELLOW"
		PREFIX="[$BOLD_RED${1}$WHITE]"
	fi
}

autoload -U colors
colors

#------------------------------------------------------------------------------------
# function precmd: Calls the other functions and creates the prompt
#------------------------------------------------------------------------------------
function precmd
{
	issucceed "$?"
	PS1="${PREFIX}[$BOLD_BLUE%n$BLACK@$BOLD_GREEN%m$BLACK]$BOLD_MAUVE%3~ $DEFAULT%# "
#	PS1="%{${fg[yellow]}%}zsh-%# %{${fg[default]}%}"

	export PS1
#	print -Pn "\e]2;%m:%~\a"
#	print -Pn "\e]0;%3~\a"
}

preexec()
{
	psvar[1]=${(V)2}
	print -Pn "\e]2;%m: %v\a"
}

# function precmd
# {
#	autoload -U finder_update
#	(finder_update &)
# }

function chpwd
{
#	echo -n "];$PWD:h:h:t/$PWD:h:t/$PWD:t"
	print -Pn "\e]0;%3~\a"
#	echo -n "];$PWD"
}

#--------------------------------------------
# Color constants used in the prompt
#--------------------------------------------
BLACK="%{[0m%}"
BOLD_BLACK="%{[1;30m%}"
RED="%{[0;31m%}"
BOLD_RED="%{[1;31m%}"
GREEN="%{[0;32m%}"
BOLD_GREEN="%{[1;32m%}"
YELLOW="%{[0;33m%}"
BOLD_YELLOW="%{[1;33m%}"
BLUE="%{[0;34m%}"
BOLD_BLUE="%{[1;34m%}"
MAUVE="%{[0;35m%}"
BOLD_MAUVE="%{[1;35m%}"
CYAN="%{[0;36m%}"
BOLD_CYAN="%{[1;36m%}"
WHITE="%{[0;37m%}"
DEFAULT="%{[0;39m%}"

PS1="[$BOLD_BLUE%n$BLACK@$BOLD_GREEN%m$BLACK]$BOLD_MAUVE%3~ %! $BLACK%# "

