#!/bin/bash

# aliases when CWD is the top of a checkout e.g. trunk or usability-dev
alias sta='$ST_CURRENT/nlw/bin/st-admin '
alias freshdev='$ST_CURRENT/nlw/dev-bin/nlwctl stop; rm -rf ~/.nlw; ./nlw/dev-bin/fresh-dev-env-from-scratch'
alias stopme='$ST_CURRENT/nlw/dev-bin/nlwctl stop'
alias startme='$ST_CURRENT/nlw/dev-bin/nlwctl start'
alias restartme='$ST_CURRENT/nlw/dev-bin/nlwctl restart'
alias svnstatus='svn status --show-updates'
alias ceqread='$ST_CURRENT/nlw/bin/ceq-read'
alias ceqstat='$ST_CURRENT/nlw/bin/ceq-stat'
alias ceqrm='$ST_CURRENT/nlw/bin/ceq-rm'

# aliases for an installed NLW
alias sww='sudo -u www-data '
alias swa='sudo -u www-data st-admin '


# convenience aliases
alias findceq='ps x  | grep ceqlotron | grep -v grep'
alias findwikis='ls ~/.nlw/root/data/'
alias cdroot='cd ~/.nlw/root'
alias cddata='cd ~/.nlw/root/data'
alias cdst='cd $ST_SRC_BASE'
alias cdconf='cd ~/.nlw/etc/socialtext'
alias cdfonts='cd $ST_CURRENT/nlw/share/fonts'
alias cdwidgets='cd $ST_CURRENT/nlw/share/widgets'
alias cdpers='cd ~/personal'
alias cdwt='cd $ST_CURRENT/nlw/share/workspaces/wikitests'

# ssskin aliases
alias cdskin='cd $ST_CURRENT/nlw/share/skin'
alias cds2='cd $ST_CURRENT/nlw/share/skin/s2'
alias cdjs='cd $ST_CURRENT/nlw/share/skin/s2/javascript'

alias svnall='cdcur; stopme; rb; freshdev; cdcur'

# alias to run Wiki Tests
# # requires stconfig dev setup and run-wiki-tests.bash
RWT=$ST_SRC_BASE/stconfig/personal/qa/run-wiki-tests.bash
alias rwt="$RWT $1 $2"
alias rwta="$RWT 'All Testcases'" 
alias rwti="$RWT 'IE Testcases'"
alias rwto="$RWT 'OSR Testcases'"

LWT=$ST_SRC_BASE/stconfig/personal/qa/run-local-wiki-tests.bash
alias lwt="$LWT "


SETSEL=$ST_SRC_BASE/stconfig/personal/qa/setup-selenium
alias setsel="source $SETSEL"

# execute wiki test
alias xwt="run-wiki-tests --timeout 60000 --plan-page "
alias xwjst='export selenium_browser=*firefox; xwt "Test Case: JS Test"; unset selenium_browser;'
alias xwjsti='export selenium_browser=*iexplore; xwt "Test Case: JS Test"; unset selenium_browser;'

# aliases to evaluate wiki tests
alias grnok="grep  -C 6 'not ok' testcases.out"
alias grtc="grep 'Loading test plan\|COMPLETED' testcases.out"
alias ttc='tail -f testcases.out'

export SVN_COMMAND='svn'

# Miscellaneous
alias lld='ls -ld'

alias psken='pstree -aAhlnp kenpier'
alias psqa1='pstree -aAhlnp qa1'
alias psqa2='pstree -aAhlnp qa2'
alias psqa3='pstree -aAhlnp qa3'
alias psqa4='pstree -aAhlnp qa4'
alias psqa5='pstree -aAhlnp qa5'
alias psqa6='pstree -aAhlnp qa6'
alias psqa7='pstree -aAhlnp qa7'
alias psqa8='pstree -aAhlnp qa8'
alias psqa9='pstree -aAhlnp qa9'
alias psqa10='pstree -aAhlnp qa10'
alias psqa11='pstree -aAhlnp qa11'
alias psqa12='pstree -aAhlnp qa12'
alias pslyssa='pstree -aAhlnp lyssa'
alias pssel='pstree -aAhlnp selenium'
alias pschris='pstree -aAhlnp cmcmahon'
alias psrick='pstree -aAhlnp rick'
alias psshahed='pstree -aAhlnp shahed'
alias psmatt='pstree -aAhlnp mheusser'

# functions
branches() {  /bin/ls /home/$1/src/st ; }
sb()        { set-branch $1; cdnlw; cd ..; }
trunkdiff () { svn diff https://repo.socialtext.net:8999/svn/socialtext/trunk https://repo.socialtext.net:8999/svn/socialtext/branches/$1 ; }

alias brqa='branches qa*'
alias ffx='ps auxww | grep firefox'
alias fsel='ps auxww | grep selenium'
