#!/bin/bash

# detect whether st-admin takes a workspace option by attempting it and
# looking at the output.  If the ouput to stderr says you need an account,
# then use the older workspace_options method of enabling socialcalc

SCWS=`st-admin enable-plugin --w admin --p socialcalc 2>&1 | grep -o account`

    if [ "$1" == "enable" ]; then 
        if [ "$SCWS" ]; then
            echo ENABLING socialcalc for all workspaces using workspace-options
            sudo mkdir -p /etc/socialtext/workspace_options
            cd /etc/socialtext/workspace_options
            for i in `/usr/bin/st-admin list-workspaces` ; do sudo mkdir -p $i ; sudo touch $i/enable_spreadsheet ; done ;
        else
            echo ENABLING socialcalc for all workspaces using st-admin
            for i in `/usr/bin/st-admin list-workspaces` ; do sudo st-admin enable-plugin --w $i --plugin socialcalc ; done ;
        fi
    elif [ "$1" == "disable" ]; then
        if [ "$SCWS" ]; then
            echo DISABLING socialcalc for all workspaces using workspace-options
            cd /etc/socialtext/workspace_options
            sudo find . -name enable_spreadsheet | sudo xargs rm -f || true
        else
            echo DISABLING socialcalc for all workspaces using st-admin
            for i in `/usr/bin/st-admin list-workspaces` ; do sudo st-admin disable-plugin --w $i --plugin socialcalc ; done ;
        fi
    else
        echo "Usage: st-socialcalc [enable|disable]"
    fi
