#!/bin/bash
# @COPYRIGHT@

DA=`sudo st-admin get-default-account | grep  -o $HOSTNAME`
if [ "$DA"  != '' ]; then
    echo default account matches $DA
else
    echo  `sudo st-admin get-default-account`
    echo "The default account should be the hostname, $HOSTNAME.  Exiting"
    exit 1
fi

WIKITESTS="/usr/share/stconfig/stbin/qa/appliance"

echo SETTING TIME
source $WIKITESTS/set-time

echo "Installing packages"
sudo apt-get install --yes st-static-files-wikitests
sudo apt-get install --yes libtest-harness-perl
sudo apt-get install --yes libaccessors-perl
sudo apt-get install --yes libtap-formatter-html-perl

echo INSTALLING and ENABLING all plugins for all accounts
sudo st-appliance-install-plugin dashboard people socialcalc signals
sudo st-admin enable-plugin --all-accounts --plugin dashboard
sudo st-admin enable-plugin --all-accounts --plugin people
sudo st-admin enable-plugin --all-accounts --plugin signals

echo INSTALLING wikitest_files
if [ ! -e /opt/wikitest_files ]; then
    sudo mkdir /opt/wikitest_files
fi
sudo unzip -u $WIKITESTS/wikitestfiles.zip  -d /opt/wikitest_files/

if [ -e /var/www/socialtext/data/test-data ]; then
    echo "DELETING old test-data workspace"
    sudo st-admin delete-workspace --w test-data  --no-export
fi
echo "IMPORTING  test-data  WORKSPACE"
sudo st-admin import-workspace --tarball $WIKITESTS/test-data.tar.gz
sudo st-admin set-workspace-config --w test-data account_name $HOSTNAME || true

if [ -e /var/www/socialtext/data/wikitests ]; then
    echo "DELETING old wikitests workspace"
    sudo st-admin delete-workspace --w wikitests --no-export
fi

echo "IMPORTING wikitests WORKSPACE"
sudo ln -sf $WIKITESTS/fast-import-pages  /usr/bin/
sudo $WIKITESTS/appliancetests-to-wiki
sudo st-admin set-workspace-config --w wikitests account_name $HOSTNAME || true

echo "SETTING user accounts to $HOSTNAME, which is supposed to be the default account"
sudo st-admin set-user-account --e wikitester@ken.socialtext.net --account $HOSTNAME
sudo st-admin set-user-account --e devnull1@socialtext.com --account $HOSTNAME

echo "GRANTING Accounts and System admin to devnull1"
sudo st-admin give-system-admin --e devnull1@socialtext.com
sudo st-admin give-accounts-admin --e devnull1@socialtext.com

echo "INSTALLING slapd"
sudo apt-get install --yes slapd

echo "ENABLING Socialcalc for all workspaces"
sudo $WIKITESTS/st-appliance-socialcalc enable

echo "SETTING all skins TO s3"
sudo st-admin set-account-config --account Socialtext skin_name s3
sudo st-admin reset-account-skin --account Socialtext --skin s3
sudo st-admin set-account-config --account $HOSTNAME skin_name s3
sudo st-admin reset-account-skin --account $HOSTNAME  --skin s3

# Make www-data own /etc/socialtext/ files so st-bootstrap-openldap will
# succeed from wikitests.
sudo chown -R www-data:www-data /etc/socialtext/

# link appliance wikitest files into the path
sudo ln -sf $WIKITESTS/st-bootstrap-openldap /usr/bin/
sudo ln -sf $WIKITESTS/st-appliance-socialcalc /usr/bin/
sudo ln -sf $WIKITESTS/st-appliance-wikitests  /usr/bin/

echo "Setting up /tmp/backup for Console Backup and Restore testing"
sudo mkdir -p /tmp/backup
sudo perl -pi -e "s#^local_archivedir: .+#local_archivedir: /tmp/backup#" /etc/socialtext/appliance.conf

echo "DONE"
