#!/bin/bash

echo "source /usr/share/stconfig/.appliance-bashrc" >> /etc/bash.bashrc
echo "PATH=$PATH:/usr/share/stconfig/stbin" >> /etc/bash.bashrc

# cp people's ssh public keys into the right place
personal="/usr/share/stconfig/personal"
for user in `ls /home`; do
    key="$personal/$user/pub.key"
    if [ -e $key ]; then
        sshdir=/home/$user/.ssh
        if [ ! -d $sshdir ]; then
            mkdir $sshdir
        fi
        cat $key >> $sshdir/authorized_keys
        chmod 0700 $sshdir
        chmod -R 0600 $sshdir/*
        chown -R $user:$user $sshdir
    fi
done

