#!/usr/local/bin/perl
use warnings;
use strict;

my $svn = $ENV{SVN_COMMAND} || 'svn';

$ENV{_SVN_DIFF_ARGS} = quotemeta "@ARGV";

if (@ARGV == 1 and $ARGV[0] =~ /^\d+$/) {
    my $r = $ARGV[0];
    my $prev = $r-1;
    @ARGV = ('-r', "$prev:$r");
}

my @command = ($svn, 'diff', @ARGV);
exec @command;
die "exec @command: $!";
