#!/usr/bin/env perl
use warnings;
use strict;
use FindBin;
use lib $FindBin::Bin;
use Wasted;

$ARGV[0] = "-r$1"
    if @ARGV and $ARGV[0] =~ /^r?(\d+)$/;

my @command = ('scm', 'log', @ARGV, '--verbose');
waste_of_time( 'scm log', sub {
        system @command;
    }
);
