#!/usr/bin/env perl
use warnings;
use strict;

$ARGV[0] = "-r$ARGV[0]"
    if @ARGV and $ARGV[0] =~ /^\d+$/;

my @command = ('scm', 'log', @ARGV, '--verbose');
exec @command;
die "exec @command: $!";
