#!/usr/bin/env perl
use warnings;
use strict;
use FindBin;
use lib $FindBin::Bin;
use Wasted;

$ENV{_SVN_DIFF_ARGS} = quotemeta "@ARGV";

if (@ARGV == 1 and $ARGV[0] =~ /^r?(\d+)$/) {
    my $r = $1;
    my $prev = $r-1;
    @ARGV = ('-r', "$prev:$r");
}

my @command = ('scm', 'diff', @ARGV);
waste_of_time( 'scm diff', sub {
        system @command;
    }
);
