#!/bin/sh
set -e
# @COPYRIGHT@

TAG=$1
TMP=`mktemp -d`
DEST_REPO=''
LINK_REPO=''
MSG='testing new package'
SSH='ssh apt.socialtext.net'

if [ -n "$TAG" ]; then
    echo Exporting $TAG
    svn -q export --force $ST_SVN/socialtext/tags/$TAG $TMP
    DEST_REPO=$TAG
    LINK_REPO='staging'
    MSG="tag: $TAG"
    APP_BRANCH=${APP_BRANCH:-"trunk"}
else 
    # Make sure we're in a good directory
    BRANCH=$(basename $(readlink ~/src/st/current))
    if [ "$BRANCH" != "trunk" ]; then
        APP_BRANCH="branches/"${APP_BRANCH:-"$BRANCH"}
    else
        APP_BRANCH=trunk
    fi
    echo "Building release for $BRANCH"
    cd ~/src/st/$BRANCH
    DEST_REPO=$BRANCH
    LINK_REPO='testing'

    # Copy current branch to temp area
    cp -vR * $TMP
fi

###################################################
# Export and Build st-appliance-update
###################################################
tempdir=`mktemp -d`
echo svn export $ST_SVN/appliance/$APP_BRANCH/st-appliance-update $tempdir/st-appliance-update
svn export $ST_SVN/appliance/$APP_BRANCH/st-appliance-update $tempdir/st-appliance-update
cd $tempdir/st-appliance-update
brett

###################################################
# Create the release repository
###################################################
echo Copy dependency packages into new testing repo
echo $SSH copy-repository deps $DEST_REPO
$SSH copy-repository deps $DEST_REPO

###################################################
# Export Appliance Build Infastructure in place
###################################################
cd $TMP/nlw
for repo in appliance-bin debian; do
    svn export $ST_SVN/appliance/$APP_BRANCH/$repo $repo
done

cd etc
svn export --force $ST_SVN/appliance/$APP_BRANCH/cron cron/
cd ..

###################
# Build Packages
###################
# create debian packages and upload using brett
brett -m "$MSG" -A $DEST_REPO

##########################
# Report the next steps
##########################
echo 
echo "#########################################################################"
echo "To queue this release for staging run this command on apt.socialtext.net:"
echo "link-repository $DEST_REPO staging"
echo
echo "To queue this release for prod run this command on apt.socialtext.net:"
echo "link-repository $DEST_REPO prod"

cd ~
rm -rf $TMP
