#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long;
use Socialtext::BuildUtils qw/notify_via_irc/;

my $reset = 0;
GetOptions(
    'r|reset' => \$reset,
);

my $log = '/var/log/wasted-time.log';
open(my $fh, $log) or die "Can't open $log: $!";
my %totals;
my $total = 0;
while (<$fh>) {
    my ($user, $time) = m/^(\w+) - (\d+)/;
    $totals{$user} += $time;
    $total += $time;
}
close $fh;

if ($total) {
    my $individuals = join ', ', map { "$_=$totals{$_}s" } keys %totals;
    notify_via_irc(sprintf 'log: Time wasted waiting for SVK recently: %s seconds (%s)', $total, $individuals);
}

if ($reset) {
    open(my $fh2, ">$log") or die "Can't open $log: $!";
    close $fh2 or die "Can't write to $log: $!";
}
