#!/bin/bash
set -x

cd ~
mkdir -p src/st
cd src/st

rm ~/.bashrc
rm ~/.bash_profile
rm ~/.zshrc
~/src/st/stconfig/stconfig-setup
. ~/.bash_profile

sudo apt-get install st-perl-deps

sudo -u postgres createuser lukec

set-branch master
