#!/usr/bin/perl
# $Id: fc_vlg,v 1.2 2005/09/13 11:45:00 mml Exp $
# Matthew M. Liggett <mml@pobox.com>

# Vim Last Grep

# USAGE (zsh at least): alias vlg='fc -e fc_vlg -30 -1'

# Then 'vlg' turns your last [efr]?grep command (in the past 30 lines)
# into
#
#   vim `grep -l YOUR_OLD_ARGUMENTS`

$filename = shift;
open F, $filename or die "$filename: $!";
while (<F>) { chomp($grep_command = $_) if /^[efr]?grep/ }

$grep_command =~ s/(\b[efr]?grep\s)(.*?-)/$1-l $2/;

open STDOUT, '>', $filename or die "$filename: $!";
print "$ENV{EDITOR} \$($grep_command)\n";
