#!/usr/bin/env perl
use warnings;
use strict;

sub usage {
    print <<'END_OF_HELP'; exit 1;
    USAGE:
        flock-cmd FLAGS LOCKFILE COMMAND [ARGS ...]
END_OF_HELP
}

my $flags = shift;
my $lockfile = shift;
usage() unless @ARGV;

open L, $lockfile or die "$lockfile: $!";
flock L, $flags or exit 0;

# Perl must be doing something before calling execve(2) that invalidates our
# flocks.  Thus, we have to use system instead of exec here to make sure the
# called program inherits our lock.
system @ARGV;
exit $?;
