#!/bin/bash -e

# USAGE: format-spinners
#
# This script looks for files in your home directory named spinner-PID.
# These are created by the show-spinners script.
#
# It formats the contents of all such files it finds in a format suitable for
# pasting into a wiki page.

cd

pids=$(
    for file in spinner-*; do
        echo $file | cut -d- -f2
    done | sort -n
)

i=0
for pid in $pids; do
    echo "* {link $pid}"
done

echo 

for pid in $pids; do
    echo "^^^^ $pid"
    echo
    echo .pre
    cat spinner-$pid
    echo .pre
done
