#!/bin/bash
#
# USAGE: grm PATTERN [other gr arguments]
#
# Runs gr looking for PATTERN, then sends output through your pager and
# highlights PATTERN.

pattern=$1
shift

gr "$pattern" "$@" | ${PAGER:-less} -p "$pattern"
