#!/bin/bash
# @COPYRIGHT@
set -e

TYPE=$1
if [ -z "$TYPE" ]; then
    echo "USAGE: make-skin-packages <hosted|appliance>"
    exit
fi

TMPDIR="/tmp/skin-$$"
mkdir $TMPDIR
cd $TMPDIR
svn export --force $ST_SVN/customer-skins/trunk share

REPO="st-prod"
SKINFILE="share/$TYPE-skins"
if [ ! -e $SKINFILE ]; then
    echo "Unknown release type: $TYPE - can't find skin file"
    exit -1;
fi

for skin in $(grep -v ^# $SKINFILE | awk {'print $1'}); do
    if [ "$TYPE" == "appliance" ]; then
        REPO=$(grep "^$skin" $SKINFILE | awk {'print $2'})
    fi
    package-skin --no-upload '$skin' '$REPO'
done

rm -rf $TMPDIR
