#!/bin/sh
set -e

REPO=$1
BRANCH=$2

if [ -z "$REPO" ] && [ -z "$BRANCH" ]; then
    echo "Usage: "
    echo "  mkbranch branch"
    echo "        - OR -"
    echo "  mkbranch repo branch"
    echo
    echo "If not given repo defaults to 'socialtext'"
    exit 1
fi

# Default to the socialtext repo.
if [ -z "$BRANCH" ]; then
    BRANCH=$REPO
    REPO="socialtext"
fi

echo "Making branch: /$REPO/branches/$BRANCH"
svn copy -m "Making branch $BRANCH" $ST_SVN/$REPO/trunk $ST_SVN/$REPO/branches/$BRANCH
