#!/bin/zsh -ef

# USAGE myerrlogs [-1|-2] [DIRECTORY]
#
#   -1      Only apache-perl logs
#   -2      Only apache2 logs
#   DEFAULT Everything
#
#   DIRECTORY defaults to ~/.nlw/log

case "$1" in
    (-1)
        subdir='apache-perl'
        shift
        ;;
    (-2)
        subdir='apache2'
        shift
        ;;
    (*)
        subdir='*'
        ;;
esac

dir=${1:-~/.nlw/log}

eval exec colorizelogs "$dir/$subdir/*.log"
