#!/bin/sh
set -e

MEGANUKE=$1
PROCS="apache apache2 apache-perl perl ceqlotron st-admin";

# Try a tamer -INT first
echo "killall -INT $PROCS"
killall -INT  $PROCS 2>&1 | grep -v "not permitted"

sleep 1

# Go for the kill
echo
echo "killall -KILL $PROCS"
killall -KILL $PROCS 2>&1 | grep -v "not permitted"

# Don't go any further unless we're in meganuke mode
if [ -z "$MEGANUKE" ]; then
    exit 0;
else
    echo
    echo "======== MEGANUKE MODE!  ========"
fi

# Delete data!
for dir in $USER/.nlw $ST_CURRENT/nlw/t/tmp t/tmp; do
    echo "Trying to delete $dir"
    rm -fR $dir
done

# Try and clean out the semaphores.  Apache leaks these sometimes.
if [ -x /usr/bin/ipcs ] && [ -x /usr/bin/ipcrm ]; then
    echo
    echo "Deleting semaphores.  Apache tends to leak these."
    for semid in `ipcs -s  | awk '{print $2}' | grep '[[:digit:]]'`; do
        echo ipcrm -s $semid
        ipcrm -s $semid
    done
fi

exit 0;
