#!/usr/bin/perl -w
use strict;
die "promptconv requres two arguments: the 'from' encoding (which is probably cp1251), and a filename"
  if @ARGV != 2;
my $enc  = shift;
my $file = shift;
die "must be in the same dir as the file to be transcoded (for now)"
  if $file =~ m{/};
0 == system("iconv -f$enc $file > /tmp/$file") or die $!;
if (system("diff -u $file /tmp/$file")) {
    $| = 1;
    print "You like? ";
    my $answer = lc(<STDIN>);
    chomp($answer);
    if ('y' eq $answer) {
        0 == system "sudo www-data mv /tmp/$file $file\n" or die $!;
    }
    else {
        print "Doing nothing because you answered '$answer'\n";
    }
}
else {
    print "Weird - no diffs\n";
    unlink "/tmp/$file" or die $!;
}
