#!/bin/zsh -ef
#
# This provides a wrapper around prove(1) that does some smart defaulting
# things for you.
#
# 0) adds -l, -r and -s by default
# 1) you can turn off -s with -S, and -r with -R
# 2) if you don't specify any tests, finds all the non-live tests under 't'

# Init.
shuffle=1
recurse=1
switches=()

# Save switches, looking especially for -S and -R.
while [[ "$1" == -* ]] {
    if [[ "$1" == -S ]] {
        shuffle=0
    } elif [[ "$1" == -R ]] {
        recurse=0
    } else {
        switches+="$1"
    }
    shift
}

# Should we shuffle?
if [[ $shuffle == 1 ]] {
    switches+=-s
}

# Find some tests to run if the user didn't give us any.
if [[ -z "$*" ]] {
    tests=${(z)$(find t -name \*.t -not -regex '^t/live.*')}
} else {
    if [[ $recurse == 1 ]] {
        switches+=-r
    }
    tests=${(z)@}
}

# Do it.
OPTIONS=""
if [ -z "$FUCK_YOU_DIAGNOSTICS_GO_TO_HELL" ]; then
    OPTIONS="$OPTIONS -Mdiagnostics"
fi
PERL5OPT=$OPTIONS exec prove -l $switches $tests
