#!/bin/bash -ex

# USAGE: push-nlw TYPE
#
# TYPE is either 'alpha' or 'beta'
#
# Run it only on prod or staging, and you should already be in a checkout
# directory.  It'll make it svn current for you.

output_file=/tmp/push-nlw.$$

type="$1"

svn_st=$(svn st)
if [ -n "$svn_st" ]; then
    echo 'Unclean checkout.  Aborting.'
    echo "$svn_st"
    exit 1
fi

branch=$(svn info | perl -lne 'print $1 if m{^URL: .*code/branches/(\S*)}')

if [ -z "$branch" ]; then
    echo 'Not a branch checkout.  Aborting.'
    exit 1
fi

svn up -q

cd nlw

dev-bin/make-release --type="$type" --source="$branch" | tee $output_file

echo <<END_OF_MSG
    Now restart the server and surf to a workspace to make sure
    everything still works okay.

    $ sudo /etc/init.d/apache-perl stop
    <UP><Return> until it's well and truly dead
    $ sudo /etc/init.d/apache-perl start

    Exit this shell to do your release blog entry.
END_OF_MSG

${SHELL:-zsh}

end_tag=$(perl -lne 'print $1 if /^Creating new tag (\S*)/' $output_file)
start_tag=$(echo "$end_tag" | perl -pe 's/(\d+)(-\d+)$/($1 - 1) . $2/e')

cat <<"EOF" > $output_file
Category: Release Blog

Replace this with your message.  Also, DOUBLE-CHECK the fetchrss entry below!
Delete entire file to abort message.

EOF
echo "{fetchrss http://talc.socialtext.net/mml/svn-rss.cgi?branch=$branch&start_tag=$start_tag&end_tag=$end_tag full}" >> $output_file

${EDITOR:-vim} $output_file

if [ "$(hostname)" == 'www.socialtext.com' ]; then
    host='prod'
else
    host='staging'
fi

[ -s "$output_file" ]

mail \
    -s "$end_tag released to $host on $(date +'%Y-%m-%d')" \
    dev-tasks@socialtext.net \
< $output_file

rm $output_file

bump-nlw-version
