#!/bin/bash
set -e

SERVER=https://www2.socialtext.net
WORKSPACE=dev-tasks

rc="$*"

if [ -z "$rc" ]; then
    SHORTNAME=`basename $0`
    cat -<<USAGE
USAGE: $SHORTNAME Foo Bar

Lets you edit a page called 'Foo Bar Release Contract' in dev-tasks.  If your
RC ends in "Release Contract" care is taken not to append it twice.  Also, a
release contract of just numbers, that is "25678" will be changed to
"rt-25678".

Examples:

# All equivalent
rc "I love cows"
rc "I love cows Release Contract"
rc "I love cows release contract"

# All equivalent
rc "12345"
rc "rt-12345"
rc "rt-12345 Release Contract"
rc "rt-12345 release CONTRACT"
rc "12345 Release Contract"
USAGE

    exit 1
fi

# Add "Release Contract" to the end if we need to:
if ! echo "$rc" | grep -i -q "Release Contract"; then
    rc="${rc} Release Contract"
fi

# Append "rt-" onto some numbers if we need to:
if echo "$rc" | egrep -i -q "^[0-9]+($| Release)"; then
    rc="rt-${rc}"
fi

echo "Creating $rc"

# TODO: It would be nice to take a branch name and possibly some other
# arguments/flags from the command line and fill in the obvious blanks in the
# template.
wikedit \
    --workspace="$WORKSPACE" \
    --server="$SERVER" \
    --template=release-contract-template \
    "$rc"

exec perl -MURI::Escape -le \
    "print '$SERVER/$WORKSPACE/index.cgi?', uri_escape('$rc')"
