#!/usr/bin/perl
use strict;
use warnings;
use lib "$ENV{ST_SRC_BASE}/current/nlw/lib";
use Term::ANSIColor;
use Getopt::Long;

my %opts;
GetOptions( \%opts,
    'quiet',
    'no-restart'
) or usage();

git_all(($opts{quiet} ? '@' : '') . 'pull --rebase');

exit;

sub git_all {
    my $cmd = shift;
    shell_run("st-git-all $cmd");
    chdir "$ENV{ST_SRC_BASE}/current";
    shell_run("git submodule init");
    shell_run("git submodule update");
}

sub color_print {
    my $color = shift;
    my $msg = shift;
    print color($color), $msg, color('reset');
}


sub shell_run {
    my $cmd = shift;
    my $nodie = $cmd =~ s/^-//;
    warn "+ $cmd\n" if $cmd =~ m/git/;
    my $rc = system $cmd;
    unless ($rc == 0) {
        color_print('red', "Error running $cmd\n");
        exit $rc unless $nodie;
    }
    return $rc == 0;
}

sub usage {
    die <<EOT;
USAGE: $0 [--quiet] [branch]

Update the current (or specified branch) across all repositories.
EOT
}
