#!/usr/bin/perl
use strict;
use warnings;
use Socialtext::Resting::Getopt qw/get_rester/;
use lib "$ENV{HOME}/src/st/trunk/nlw/lib";
use Socialtext::System qw/shell_run/;
use Term::ANSIColor;

my $src_base = $ENV{ST_SRC_BASE} || "$ENV{HOME}/src/st";
my $r = get_rester();

my $dead_branch = shift;
usage() unless $dead_branch;

# then delete my working copy of the branch
print color('bold red'),
    "Ctrl-C now to not remove the branch from svn and locally\n\n",
    "Press enter to delete the branch...\n", color('reset');
<STDIN>;

my @repo_names = qw/socialtext control appliance socialtext-reports/;
for my $repo (@repo_names) {
    my $branch_path = "//mirror/$repo/branches/$dead_branch";

    eval {
        shell_run("svk rm -m 'remove-branch $dead_branch' $branch_path");
    };
    next if $@;

    if ($repo eq 'socialtext') {
        shell_run("rm -rf $src_base/$dead_branch");
    }
    else {
        $repo =~ s/^socialtext-//;
        shell_run("svk up -s $src_base/$repo");
    }
}

# remove it from the testrunner?
# -- not supported yet --

# Check the release contract for something?
# -- not supported yet --

exit;

sub usage {
    die <<EOT;
$0 <rester options> branch-to-remove

Removes the specified branch from all repositories.
EOT
}


