#!/bin/bash

basedir=~/.nlw
touchfile=$basedir/.lastrestart


if [ ! -f $touchfile ]; then
    touch $touchfile
    nlwctl -1 restart
    exit
fi

mods=`find lib -follow -newer $touchfile | head -1`
if [ ! -z $mods ]; then
    touch $touchfile
    nlwctl -1 restart
    exit
fi
