#!/bin/bash
# restarts apache as needed
# if an argument is specified, sleeps that argument before trying again

delay=${1-0}

basedir=~/.nlw
touchfile=$basedir/.lastrestart

restartit() {
    if [ ! -f $touchfile ]; then
        touch $touchfile
        nlwctl -1 restart
        exit
    fi

    mods=`find ~/src/st/socialtext/nlw/lib -follow -newer $touchfile | head -1`
    if [ ! -z $mods ]; then
        touch $touchfile
        nlwctl -1 restart
        exit
    fi
}

if [ $delay == 0 ]; then
    restartit
else
    while true; do
        restartit
        sleep $delay
    done
fi
