#!/bin/sh -e
# This does what you wish 'rm -rf' would do.  It doesn't ever stop to ask you
# questions ("do you really want to 'override permissions'?"), but it warns
# you and exits nonzero if it can't remove something.
(
    for path in "$@"; do
        find "$path" -depth
    done
) \
| perl -lne '
    BEGIN { sub bye() { (-d) && ! (-l) ? rmdir : unlink } }
    if (not bye) {
        warn "rmr: $_: $!\n";
        $code = 1;
    }
    END { exit $code }
'
