#!/bin/sh
set -e

# Backup if we're in the nlw dir
if [ -d "./dev-bin" ]; then
    cd ..
fi

# If we can't see the nlw dir now, we're in the wrong place
if [ ! -d "nlw" ]; then
    echo "This does not appear to be an NLW checkout!"
    exit 1;
fi

# Clean house!
scm status --no-ignore | awk '{print $2}' | xargs rm -fR
scm revert -R .
if [ -d ".svn" ]; then
    svn update
else
    svk update -s
fi

echo "Scrubbed"
scm status --no-ignore
