#!/usr/bin/perl
use strict;
use warnings;
use File::Path qw/mkpath/;
use Fatal qw/:void mkpath chdir unlink symlink/;

sub usage {
    die <<EOT;
set-branch branch
EOT
}

my $branch = shift;
my $private = shift;
usage() unless $branch;

my $src_base   = $ENV{ST_SRC_BASE};
unless (-d $src_base) {
    mkpath $src_base;
}

my $branch_dir = "$src_base/$branch";
unless (-d $branch_dir) {
    print "$branch_dir doesn't exist.  Run $ENV{SVN_COMMAND} checkout? [Y/n]\n";
    my $ans = <STDIN>;
    if ($ans =~ m/^y|\s*$/i or ($ans) == 0) {
        if ($branch eq 'trunk') {
            checkout($branch);
        }
        elsif ($private) { 
            checkout("private-branches/$branch");
        }
        else {
            checkout("branches/$branch");
        }
    }
    else {
        print "Bye!\n";
        exit;
    }
}

if (-d $branch_dir) {
    my $curlink = "$src_base/current";
    unlink $curlink if -l $curlink;
    symlink $branch_dir, $curlink;
}
exit;

sub checkout {
    my $branch_path = shift;
    chdir $src_base;
    my $cmd = "scm checkout '$ENV{ST_CODE_REPO}/$branch_path'";
    print "Running $cmd\n";
    system($cmd);
}
