#!/bin/sh

# use this script to set git username and password for git commits and pushes

echo -n "git username: " 
read GUSER
echo -n "git email: "
read GEM
#echo $GUSER $GPWD

echo git config --global user.name \""$GUSER"\"
echo git config --global user.email "$GEM"

git config --global user.name \""$GUSER"\"
git config --global user.email "$GEM"
echo ""
