#!/bin/bash

# heuristic in the awk below is:
# niceness is 18 ($4==18) AND
# accumulated time is at least double digit minutes
for pid in `top -n1 -bu www-data | awk '$4==18 && $11 ~ /[0-9][0-9]:/  {print $1}'`
do
        procdir="/proc/$pid"
        (
        echo status: $pid
        sudo cat $procdir/status
        sudo ls -alrt $procdir
        echo ls -lart $procdir/fd
        sudo ls -lart $procdir/fd
        ) > ~/spinner-$pid
done
