#!/bin/sh
set -e
BRANCH=$1

if [ -z "$BRANCH" ]; then
    echo "Usage: $0 branch-name (or 'trunk') "
    exit 1
fi

if [ "$BRANCH" = "trunk" ]; then
    echo "$ST_CODE_REPO/trunk"
else
    echo "$ST_CODE_REPO/branches/$BRANCH"
fi
