#!/usr/local/bin/perl

use strict;
use warnings;

sub tidy {
    my $file = shift;
    my @cmd = (
        'perltidy',
        '-l=78',
        '-i=4',
        '-ci=4',
        '-se',
        '-b',
        '-bar',
        '-boc',
        '-vt=0',
        '-vtc=0',
        '-cti=0',
        '-pt=1',
        '-bt=1',
        '-sbt=1',
        '-bbt=1',
        '-nolq',
        '-npro',
        '-nsfs',
        '-wbb="% + - * / x != == >= <= =~ !~ < > | & >= < = **= += *= &= <<= &&= -= /= |= >>= ||= .= %= ^= x="',
    );
    push @cmd, $file
      if $file;
    system @cmd
      and die "Cannot run perltidy on $file: $!";
}

if (@ARGV) {
    tidy $_ for @ARGV;
}
else {
    tidy;
}
