#!/usr/bin/perl -wl
use strict;
my @default_env = (
    [ ST_TRUNK => '$HOME/src/st/trunk' ],
    [ PATH => join ':', qw(
        ~/stbin
        ~/bin
        ~/local/bin
        /usr/local/bin
        $ST_TRUNK/nlw/bin
        $ST_TRUNK/nlw/dev-bin
        $PATH
    ) ],
    [ NLW_TEST_FASTER => '1' ],
    [ REMOTE_USER => 'devnull1@socialtext.com' ],
    [ EDITOR => 'vim' ],
    [ VISUAL => 'vim' ],
    [ TEST_LESS_COMMENT => '\'$d -- $u\'' ],
    [ COLOR => '32' ],
    [ SCREENCOLOR => 'g' ],
);
push @default_env, [ 'LD_LIBRARY_PATH' => '/usr/lib/debug:$LD_LIBRARY_PATH' ]
  if -e '/usr/lib/debug';

for my $pair (@default_env) {
    my ($name, $value) = @$pair;
    print "export $name=$value"
      unless $ENV{$name}; # make sure to respect ~/.stconfig-before settings
}
