#!/bin/sh
set -e


BRANCH=$1
KIND=${2:-"release"}
MSG=${3:-""}

if [ -z "$BRANCH" ]; then
    echo "Usage: $0 branch [prefix [message [version [verbose]]]]"
    exit 1
fi

if [ "$BRANCH" = "-c" ]; then
    BRANCH=`perl -le '$b = readlink("$ENV{ST_SRC_BASE}/current"); $b =~ s(.+/)(); print $b'`
fi
if [ ! -d "$ST_SRC_BASE/$BRANCH" ]; then
    echo "The branch you specified ($BRANCH) must be checked out!";
    exit 1;
fi

VERSION=${4:-$(st-version $BRANCH)}
if [ -z "$VERSION" ]; then
    echo "Error: Could not determine version for $BRANCH";
    exit 1;
fi

TAG=`get-next-release-tag $KIND $VERSION`
if [ -z "$TAG" ]; then
    echo "Error: Could not determine next $KIND tag for $BRANCH";
    exit 1;
fi

VERBOSE=${5:-""}

echo -n "Tag branch $BRANCH as $TAG? [yN] "
read answer
if [ "$answer" != "y" ]; then
    exit
fi

MESSAGE="Creating tag $TAG from $BRANCH $MSG"
st-git-all tag -a $TAG -m "$MESSAGE"
st-git-all push --tags
