#!/bin/sh
set -e


BRANCH=$1
KIND=${2:-"release"}
MSG=${3:-""}

if [ -z "$BRANCH" ]; then
    echo "Usage: $0 branch [prefix [message [version [verbose]]]]"
    exit 1
fi

VERSION=${4:-$(st-version $BRANCH)}
if [ -z "$VERSION" ]; then
    echo "Error: Could not determine version for $BRANCH";
    exit 1;
fi

TAG=`get-next-release-tag $KIND $VERSION`
if [ -z "$TAG" ]; then
    echo "Error: Could not determine next $KIND tag for $BRANCH";
    exit 1;
fi

VERBOSE=${5:-""}

echo -n "Tag branch $BRANCH as $TAG? [yN] "
read answer
if [ "$answer" != "y" ]; then
    exit
fi

for REPO in `st-repo-list` ; 
do
    
    MESSAGE="Copying /$REPO/branches/$BRANCH to /$REPO/tags/$TAG $MSG"
    BRANCH_URL="$ST_SVN/$REPO/branches/$BRANCH"
    TAG_URL="$ST_SVN/$REPO/tags/$TAG"
   
    if [ $VERBOSE ]; then
        echo Message: $MESSAGE
        echo From: $BRANCH_URL
        echo To: $TAG_URL
    fi

    if svn -q copy -m "$MESSAGE" $BRANCH_URL $TAG_URL >/dev/null; then
        echo "Created $REPO tag $TAG from branch $BRANCH"
    fi

done

