#!/bin/sh
set -e

BRANCH=$1
VERSION=$2
if [ -z "$BRANCH" ] || [ -z "$VERSION" ]; then
    echo "Usage: $0 branch version"
    exit 1
fi

REPOS="{socialtext,socialtext-skins,socialtext-reports,control,appliance}"
TAG=$(get-next-release-tag  test  $VERSION)

for REPO in  {socialtext,socialtext-skins,socialtext-reports,control,appliance} ;

do

    # Create the repo tag from the repo branch
    
    MESSAGE="Copying /$REPO/branches/$BRANCH to /$REPO/tags/$TAG."
    BRANCH_URL="$ST_SVN/$REPO/branches/$BRANCH"
    TAG_URL="$ST_SVN/$REPO/tags/$TAG"
    
    if svn -q copy -m "$MESSAGE" $BRANCH_URL $TAG_URL >/dev/null; then
        echo "Created $REPO tag $TAG from branch $BRANCH"
    fi
    
done
