#!/bin/bash -e

usage() {
    cat <<END_OF_HELP
USAGE:
    test-branch add stable-1.8.1
    test-branch (remove|rm) exp-ruby-rewrite
    test-branch status trunk
    test-branch htstatus stable-1.8.2
    test-branch (list|ls)
END_OF_HELP
    exit 0
}

verb="$1"
branch="$2"

DIR=$(dirname $0)
CHECKOUTS=~testrunner/checkouts

case "$verb" in
    (a|ad|add)
        [ -z "$branch" ] && usage
        [ ! -d ~testrunner/$branch ]
        [ ! -d ~testrunner/$CHECKOUTS/$branch ]
        sudo su - testrunner "
            LANG=en_US.UTF-8 \
            svn co $ST_CODE_REPO/branches/$branch \
            && mv $branch $CHECKOUTS
        "
        ;;
    (r|rm|re|rem|remo|remov|remove)
        [ -z "$branch" ] && usage
        sudo su - testrunner "
            mv $CHECKOUTS/$branch . \
            && rm -fr $branch
        "
        ;;
    (s|st|sta|stat|statu|status)
        [ -z "$branch" ] && usage
        db2lines $CHECKOUTS/$branch/test.db \
        | perl -F, -alne ' 
            eval qq( \$$F[0]\{\$F[1]\} = \$F[2] );
            END {
                foreach $test (sort keys %lastpass) {
                    print
                        $status{$test} eq q(passing) ? q(+) : q(-),
                        "$lastpass{$test} $test";
                }
            }
        '
        ;;
    (h|ht|hts|htst|htsta|htstat|htstatu|htstatus)
        [ -z "$branch" ] && usage
        db2lines $CHECKOUTS/$branch/test.db \
        | perl -F, -alne ' 
            eval qq( \$$F[0]\{\$F[1]\} = \$F[2] );
            END {
                print
                    qq(<TITLE>'"$branch"'</TITLE>\n),
                    q(<TABLE>),
                    q(<TR><TH colspan=2>'"$branch"'</TH>),
                    q(<TH colspan=4>'"$(date +%Y-%m-%d\ %H:%M:%S)"'),
                    q(</TH></TR>);
                $i = 0;
                foreach $test (sort keys %lastpass) {
                    ++$i;
                    print q(<TR>) if ($i % 3 == 1);
                    print
                        q(<TD bgcolor=),
                        $status{$test} eq q(passing) ? q(green) : q(red),
                        ">$lastpass{$test}</TD><TD>$test</TD>";
                }
                print q(</TABLE>);
            }
        '
        ;;
    (l|ls|li|lis|list)
        cd $CHECKOUTS
        ls -d */
        ;;
    (*)
        usage
        ;;
esac
