#!/usr/bin/perl
use strict;
use warnings;
use lib "$ENV{HOME}/src/st/current/nlw/lib";
use Socialtext::System qw/shell_run/;
use Getopt::Long;

my %opts;
GetOptions( \%opts,
    'pretend',
    'message=s',
    'from=s',
) or usage();

my $branch = shift;
usage() unless $branch;

my $branch_path = "//mirror/socialtext/branches/$branch";
my $from_branch = $opts{from} ? "branches/$opts{from}" : "trunk";
my $from_dir = $opts{from} || 'trunk';
my $smerge_opts  = $opts{pretend} ? '-C ' : '';

$opts{message} ||= "update-branch $branch from $from_branch";
$smerge_opts .= "-m '$opts{message}'";

map { shell_run($_) }
    "svk up -s ~/src/st/$from_dir",
    "svk up -s ~/src/st/$branch",
    "svk smerge $smerge_opts //mirror/socialtext/$from_branch $branch_path",
    "svk up -s ~/src/st/$branch",
    "cowsay 'Branch $branch updated!'",
    ;

exit;

sub usage {
    die <<EOT;
$0 [rester options] [options] new-branch-name

options:
  --pretend     don't really do the merge (svk smerge -C)
  --from        branch to update from (default: trunk)
EOT
}
