#!/usr/bin/perl -w
use strict;
my @mods = map {
    s/^.\s*//; chomp; $_
} grep /^[MA?]/, slurp('scm st|');
die "(No modified files.)\n" unless @mods;
system 'vim', '-o', @mods;

sub slurp {
    my $file = shift;
    open my $fh, $file or die "Could not open $file: $!\n";
    return <$fh>;
}
