#!/bin/bash -e

# USAGE: wiki-spinners
#
# This script shows you all the spinner-PID files in your home directory,
# gives you the option to bail out first, and then emails a wikitext formatted
# version of their contents to the st-spinners workspace.

cd

ls -l spinner-*

echo
echo
echo RETURN to proceed.  ^C to bail.
read

format-spinners \
| mail -s "$(date +'%Y-%m-%d') $(hostname) procfs data" \
    st-spinners+procfs@socialtext.net
