#!/usr/local/bin/perl
use warnings;
use strict;

use Fcntl ':flock';

sub usage {
    print <<'END_OF_HELP';
    USAGE:
        with-lock LOCKFILE COMMAND [ARGS ...]

        Blocks until exclusive lock is acquired on LOCKFILE.  Exits nonzero
        immediately if LOCKFILE does not exist.  Otherwise, execs COMMAND with
        ARGS (the lock will continue to be held after the exec).  When COMMAND
        exits, the lock will automatically be released.
END_OF_HELP
    exit 0;
}

usage() if @ARGV < 2;

exec 'flock-cmd', LOCK_EX, @ARGV;
