#!/usr/local/bin/perl

use strict;
use warnings;

sub tidy {
    my $file = shift;
    my @cmd = ( 'perltidy', '-b', '-bar', '-nsfs', '-nolq', '-npro' );
    push @cmd, $file
      if $file;
    system @cmd
      and die "Cannot run perltidy on $file: $!";
}

if (@ARGV) {
    tidy $_ for @ARGV;
}
else {
    tidy;
}
